<?php

namespace Database\Seeders;

use App\Models\AboutSettings;
use App\Models\Experience;
use App\Models\HeroSettings;
use App\Models\Project;
use App\Models\TechStack;
use Illuminate\Database\Seeder;

class PortfolioSeeder extends Seeder
{
    public function run(): void
    {
        HeroSettings::create([
            'headline' => 'ENGINEERING',
            'subheadline' => 'THE INVISIBLE',
            'tagline' => 'SYSTEM ONLINE',
            'description' => 'I am Alex. A software engineer and systems architect specializing in high-performance infrastructure and minimalist brutalist interfaces. Code as structural art.',
            'status' => [
                'Deploying scalable microservices.',
                'Optimizing rust binaries.',
                'Seeking complex problems.',
            ],
            'core_stack' => ['Rust', 'TypeScript', 'Go', 'React', 'k8s'],
        ]);

        AboutSettings::create([
            'header' => 'SYSTEM.INFO',
            'competencies_header' => 'Core_Competencies',
            'concrete_image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDRmWA4JFr8WRvWeIqdRgLyTZUL78ImP926YBllFIGcKhjo7Zx_iQ0A3kOxVK8Asvjyg3mhMl3uu59ahTiwy9ne4znrCBdsmcyMjdYVEnPUxNGjQvvBr-OGudC74L_L92LaRdt7bSk1wSE5wdsPVrvaL1VoSkamUJlLPt9a3FCwBEYcaorxT2FwbZTg9PJDJi2Kv5Q4RUZSCCk7q1QfOYWEXi0NLNALqwtU4dPnmjuPRjQR6ydtZDM4FEPSpm0U2NXet1j-LPhGPhXN',
            'paragraphs' => [
                'I engineer scalable architectures and build uncompromising digital interfaces. My focus is on creating systems that are performant, resilient, and structurally sound. I believe in minimalism not as an aesthetic choice, but as an operational necessity—removing complexity to reveal clarity.',
                'With over a decade of experience bridging the gap between back-end infrastructure and front-end execution, I specialize in distributed systems, modern web frameworks, and creating developer tools that accelerate velocity.',
                'When I\'m not writing code, I\'m analyzing system logs, optimizing compile times, or studying brutalist architecture.',
            ],
            'competencies' => [
                'System Architecture & Design',
                'High-Performance Web Applications',
                'API Development (REST, GraphQL, gRPC)',
                'Database Optimization & Scaling',
                'UI/UX Engineering (Component Driven)',
            ],
            'sys_config_location' => 'San Francisco, CA',
            'sys_config_timezone' => 'PST (UTC-8)',
            'sys_config_status' => 'Available for contract',
            'sys_config_languages' => ['TypeScript', 'Rust', 'Go', 'Python'],
            'sys_config_frameworks' => ['React', 'Next.js', 'Node.js', 'TailwindCSS'],
        ]);

        Experience::insert([
            [
                'slug' => 'stellar-dynamics',
                'role' => 'Senior Systems Engineer',
                'company' => 'Stellar Dynamics Inc.',
                'period' => '2021 — PRESENT',
                'bullets' => json_encode([
                    'Architected microservices infrastructure scaling to 5M+ daily requests, reducing latency by 40%.',
                    'Led a team of 5 engineers in migrating legacy monolith to Kubernetes-orchestrated containers.',
                    'Implemented zero-downtime deployment pipelines using GitHub Actions and ArgoCD.',
                ]),
                'technologies' => json_encode(['Go', 'Kubernetes', 'AWS']),
                'position' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'quantum-analytics',
                'role' => 'Full Stack Developer',
                'company' => 'Quantum Analytics',
                'period' => '2018 — 2021',
                'bullets' => json_encode([
                    'Developed real-time data visualization dashboards for enterprise clients using React and D3.js.',
                    'Designed and optimized RESTful APIs in Node.js, improving data retrieval speeds by 60%.',
                ]),
                'technologies' => json_encode(['React', 'Node.js', 'PostgreSQL']),
                'position' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'nexus-tech',
                'role' => 'Backend Engineer',
                'company' => 'Nexus Technologies',
                'period' => '2016 — 2018',
                'bullets' => json_encode([
                    'Maintained and refactored core backend services written in Python.',
                    'Collaborated with data science team to integrate machine learning models into production environments.',
                ]),
                'technologies' => json_encode(['Python', 'Django', 'Redis']),
                'position' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Project::insert([
            [
                'slug' => 'neural-net-api',
                'title' => 'NEURAL_NET_API',
                'description' => 'High-throughput inference API for distributed machine learning models. Built to handle 10k+ concurrent requests with sub-50ms latency.',
                'image_url' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo8nt8q_hEeoX7WSeiFwRP7f1ktgJzFtQh6skqH5WgZXPoZhtxPaZhkWxvum8Nll9XEQ4D83HsrELU_w7dMJIiZlGxtOEhYQ-5m3GMMefmpn-332mt-X0xTHHnyEpwUcAlTbrtwY3h5K13bSUkP2BCwJie71g4c2hjkRG7mFw75nqjUcXO1HCriUaCozCzTJY0Zu7gzs7AIYwJvwlzedk61gjyN2Eke7x7tNvMnRefHtsXq7oTotvotWO8bQ91_fVm9KTj6d_w7tEK',
                'status' => 'production',
                'github_url' => 'https://github.com/alex-dev/neural-net-api',
                'demo_url' => '#',
                'details' => 'This system compiles down to highly optimized binaries. It leverages cross-beam channels for lock-free concurrency and stores transient weight indices in a memory-mapped cache.',
                'tags' => json_encode(['Rust', 'gRPC', 'Redis']),
                'position' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'synapse-db',
                'title' => 'SYNAPSE_DB',
                'description' => 'Custom distributed key-value store optimized for read-heavy workloads. Implements a bespoke Raft consensus algorithm for fault tolerance.',
                'image_url' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3U-4I-YMfWwCEwkcoMwC3bP3BvmQLO-dE4vL0TOYsOYxUuKZkcaLEfGq0oLJRLGLcSW7X26eUbZs9CD_Lo_3EXAPop1bK8ieuMwguV-Dt46bIVGq6Va_RMfqleW9jI9qtDTwFZ4tjvqUH1khHN6aSxErYR6oGrbPajzje9E50so3t5tij6WWcyaA2iXBp-XEhf2YLjjevwlj6xoQNMwOfwj5AyMfHAFikmO6PpQ_GdD9NzicYyXjGFDxdKpKi3T9gCoTD3PWzbFRU',
                'status' => 'production',
                'github_url' => 'https://github.com/alex-dev/synapse-db',
                'demo_url' => '#',
                'details' => 'A clean implementation of Raft consensus with leader election, log replication, and safe state machines. Features dynamic cluster membership changes and auto-snapshotting of key spaces.',
                'tags' => json_encode(['Go', 'Raft', 'LevelDB']),
                'position' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'quantum-router',
                'title' => 'QUANTUM_ROUTER',
                'description' => 'Layer 7 load balancer with predictive routing capabilities. Uses ML to dynamically adjust traffic paths based on historical anomaly data.',
                'image_url' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAB0nsdb2wBloqC7V4Z-Zn-9c-b05q1aZ3xrPypUZ-C332WiMmz7w80NslZV2ng1OcJTESLMk0UHdCSyw0wyaxjURt8kPk_CCWDBUIa3q6BnYOxj7Izf8lFkxC3JM76bDa1m_visoUY0Qqa86yNa1EVk_BRwRVZo5GQtMODh6lrfkSH2_nOWwDPurQNMlVhpnptHIj2gH8gdgpavQLgz2ajTKIiTPtTZ-IHT7rl9QuTlDqL0FH6cfSZA8qwTEoOmNEMXL0RrQVXu1Fr',
                'status' => 'production',
                'github_url' => 'https://github.com/alex-dev/quantum-router',
                'demo_url' => '#',
                'details' => 'Utilizes Linux eBPF filters for ultra-fast kernel-level packet inspection, feeding metrics into an inline neural network proxy modeled on raw TCP flow signatures.',
                'tags' => json_encode(['C++', 'eBPF', 'Envoy']),
                'position' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'void-ui-library',
                'title' => 'VOID_UI_LIBRARY',
                'description' => 'Headless UI component library built for extreme performance and zero runtime overhead. Strictly unstyled, providing structural primitives.',
                'image_url' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2tpFIeg9KDx1FjD0pF1w3kLHohOIc3ZePsyZ_QQyJhkaa6lJBIWeJkGFPaajxgpQYC9UM3Ssh_NQ_RIC_kYKKwT6N3g6vOv-b29P7W-W1uG7IeCfBu0V6-sKWDVDNDF3AvoYQKks7T60KyXDIRNM8NegVV223YJ-LK_r1dl0MLZu8818Q3CcrD6YNqZDSn61HoC2MTsqthK_f2o9-zeXOzql5_ouEH8NtG3dZTiCTaOSejcmQenPVqrT5K984PUP7RA0SMU6uCqwn',
                'status' => 'production',
                'github_url' => 'https://github.com/alex-dev/void-ui-library',
                'demo_url' => '#',
                'details' => 'Focuses entirely on standard accessibility tree hooks and focus state managers. It includes no pre-packaged theme styles, which yields a bundle weight of just 1.2kB gzipped.',
                'tags' => json_encode(['TypeScript', 'React', 'Tailwind']),
                'position' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        TechStack::insert([
            [
                'type' => 'core',
                'name' => 'React',
                'icon' => 'Code',
                'description' => 'v18.x / Concurrent Mode',
                'version' => null,
                'index_label' => '01',
                'role' => null,
                'bullets' => null,
                'position' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'core',
                'name' => 'TypeScript',
                'icon' => 'Braces',
                'description' => 'Strict Mode Enabled',
                'version' => null,
                'index_label' => '02',
                'role' => null,
                'bullets' => null,
                'position' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'core',
                'name' => 'Next.js',
                'icon' => 'Globe',
                'description' => 'App Router / SSR',
                'version' => null,
                'index_label' => '03',
                'role' => null,
                'bullets' => null,
                'position' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'featured',
                'name' => 'Tailwind CSS',
                'icon' => 'Palette',
                'description' => 'Utility-first styling for rapid, consistent UI development. Custom design system integration.',
                'version' => null,
                'index_label' => 'UI',
                'role' => null,
                'bullets' => json_encode(['JIT Compiler', 'Custom Tokens', 'CSS Variables']),
                'position' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'backend',
                'name' => 'Node.js',
                'icon' => 'Cpu',
                'description' => 'Runtime Environment',
                'version' => null,
                'index_label' => null,
                'role' => null,
                'bullets' => null,
                'position' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'backend',
                'name' => 'Python',
                'icon' => 'Terminal',
                'description' => 'Data & Scripting',
                'version' => null,
                'index_label' => null,
                'role' => null,
                'bullets' => null,
                'position' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'backend',
                'name' => 'PostgreSQL',
                'icon' => 'Database',
                'description' => 'Relational Data',
                'version' => null,
                'index_label' => null,
                'role' => null,
                'bullets' => null,
                'position' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'backend',
                'name' => 'Redis',
                'icon' => 'HardDrive',
                'description' => 'Caching Layer',
                'version' => null,
                'index_label' => null,
                'role' => null,
                'bullets' => null,
                'position' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'infrastructure',
                'name' => 'Docker',
                'icon' => null,
                'description' => null,
                'version' => null,
                'index_label' => null,
                'role' => 'Containerization',
                'bullets' => null,
                'position' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'infrastructure',
                'name' => 'AWS',
                'icon' => null,
                'description' => null,
                'version' => null,
                'index_label' => null,
                'role' => 'Cloud Provider',
                'bullets' => null,
                'position' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'infrastructure',
                'name' => 'Vercel',
                'icon' => null,
                'description' => null,
                'version' => null,
                'index_label' => null,
                'role' => 'Edge Deployment',
                'bullets' => null,
                'position' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'tooling',
                'name' => 'Git',
                'icon' => null,
                'description' => null,
                'version' => null,
                'index_label' => null,
                'role' => 'Version Control',
                'bullets' => null,
                'position' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'tooling',
                'name' => 'Vite',
                'icon' => null,
                'description' => null,
                'version' => null,
                'index_label' => null,
                'role' => 'Build Tool',
                'bullets' => null,
                'position' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'tooling',
                'name' => 'Figma',
                'icon' => null,
                'description' => null,
                'version' => null,
                'index_label' => null,
                'role' => 'UI Design',
                'bullets' => null,
                'position' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
